### ISSUE TITLE
Bug when minimizing in rewriter?

### ISSUE THREAD

**Issue by SkySkimmer** [JasonGross/coq-tools#156]
https://github.com/coq/coq/pull/17346#issuecomment-1533755349 has Qed lemmas left

**Comment by JasonGross** [comment]
I'm not sure this is a bug in the minimizer?  It seems just as likely that it's a bug in the runner infrastructure or in Coq itself, or perhaps in the way the rewriter is set up. The actual issue is that when minimization resumed, when it ran
```
/github/workspace/builds/coq/coq-passing/_install_ci/bin/coq_makefile COQC = /github/workspace/builds/coq/coq-passing/_install_ci/bin/coqc.orig COQDEP = /github/workspace/builds/coq/coq-passing/_install_ci/bin/coqdep -o Makefile44j2imgx.coq -R /github/workspace/builds/coq/coq-passing/_build_ci/rewriter/src/Rewriter Rewriter -Q /github/workspace/cwd Top -Q /github/workspace/builds/coq/coq-passing/_install_ci/lib/coq/user-contrib/Ltac2 Ltac2 -Q /github/workspace/builds/coq/coq-passing/_install_ci/lib/coq/user-contrib/Rewriter Rewriter -I /github/workspace/builds/coq/coq-passing/_build_ci/rewriter/src/Rewriter/Util/plugins -R /github/workspace/builds/coq/coq-passing/_build_ci/rewriter/src/Rewriter Rewriter -Q /github/workspace/cwd Top -Q /github/workspace/builds/coq/coq-passing/_install_ci/lib/coq/user-contrib/Ltac2 Ltac2 -Q /github/workspace/builds/coq/coq-passing/_install_ci/lib/coq/user-contrib/Rewriter Rewriter -I /github/workspace/builds/coq/coq-passing/_build_ci/rewriter/src/Rewriter/Util/plugins -arg -q -arg -w -arg +implicit-core-hint-db,+implicits-in-term,+non-reversible-notation,+deprecated-intros-until-0,+deprecated-focus,+unused-intro-pattern,+deprecated-hint-constr,+fragile-hint-constr,+variable-collision,+unexpected-implicit-declaration,+omega-is-deprecated,+deprecated-instantiate-syntax,+non-recursive,+deprecated-hint-rewrite-without-locality,+deprecated-hint-without-locality,+deprecated-instance-without-locality,+undeclared-scope,+deprecated-typeclasses-transparency-without-locality,+future-coercion-class-field,unsupported-attributes -arg -w -arg -notation-overridden,-unusable-identifier -arg -w -arg -notation-overridden -arg -w -arg -deprecated-native-compiler-option -arg -native-compiler -arg ondemand bug_01.v
```
followed by
```
make -k -f Makefile44j2imgx.coq KEEP_ERROR=1 bug_01.glob
```
the result was (after many "required file matches multiple file in path" warnings)
```
*** Error: 
in file bug_01.v, could not find META.coq-rewriter.
make: *** No rule to make target 'bug_01.glob'.
```
and as a result the minimizer was unable to understand the `Require`s.  So because `coqdep` fails fatally with this error, `make` never gets around to making the `.glob` file.

**Comment by JasonGross** [comment]
@SkySkimmer Do you agree that this seems to be a bug in Coq? (https://github.com/coq/coq/issues/17567)  Or am I doing something wrong in my invocation of `make`?

**Comment by SkySkimmer** [comment]
The invocation of coq_makefile seems wrong, it should mention the META file (as it is in the _CoqProject)

**Comment by SkySkimmer** [comment]
Alternatively you might be able to set some ocamlfind variable so that it can find the already compiled plugin, but I think that might need the file to be called `rewriter/META` instead of `META.rewriter` so seems less feasible.

**Comment by JasonGross** [comment]
I don't think finding the `META` file is feasible, as it's path is never passed to `coqc`.  Instead, we should add an argument `--make-globs-without-coq-makefile` that is always passed by CI minimization and which bypasses the use of `coq_makefile` to generate the globs.

**Comment by JasonGross** [comment]
Given that we already pass `--no-deps` at https://github.com/coq-community/run-coq-bug-minimizer/blob/d4c2c4efbc96225c2730c998234c180cea91dfc8/run-script.sh#L228, #157 should fix this issue once it auto-merges

**Comment by SkySkimmer** [comment]
https://github.com/coq/coq/pull/17346#issuecomment-1535513231 is better but still seems bugged, for instance
~~~coq
Example ex1 : forall x : nat, x = x.
Proof.
  Rewrite_for norules.
  lazymatch goal with
  | |- ?x = ?x => is_var x; reflexivity
  end.
Qed.
~~~
can be removed
