### ISSUE TITLE
inlining is incomplete

### ISSUE THREAD

**Issue by RalfJung** [JasonGross/coq-tools#20]
Steps to reproduce:
* Check out https://gitlab.mpi-sws.org/FP/iris-coq.git
* Go to commit 6959103
* Run `find-bug.py -Q . "" modures/cofe.v test.v` (there's a stupid typo in that file, just to see if the minimizing works)

Expected behavior:
The resulting file is a self-contained file that only imports base Coq libraries (so that it can be used to submit a bug).

Actual behavior:
The resulting file does `Require prelude.base.`, i.e., it still depends on other local files from this development. I don't have the entire output any more, if you need it, I can run this again.

Note that the dependencies go something like this:
modures.cofe -> modures.base -> prelude.prelude -> (prelude.base + lots of other stuff in prelude).
So quite amazingly, the tool figured out that all the other stuff brought in by prelude.prelude is not needed. This is awesome, since those imports amount to ~9000 lines. But for some reason, it stopped there and did not inline prelude.base.

If I call find-bug with `--no-minimize-before-inlining`, then the file it generates contains *everything* inlined, and the file compiles correctly (as in, it shows the bug as expected). So in principle, inlining does the job correctly, it just doesn't seem to go all the way in the default mode (`--minimize-before-inlining`).

**Comment by JasonGross** [comment]
Do you have a reproducing test case that doesn't depend on ssr / mathcomp / other non-bundled libraries?

The issue is that it tries to inline `prelude.base`, but, for whatever reason, the resulting file doesn't preserve the error message.  (There can be a variety of reasons for this, for example #16.)  Since it does no good to inline the dependencies of `prelude.base` without inlining `prelude.base` itself, it stops there.  (Actually, it'll try to inline all of its dependencies, but it'll see that, after removing things, doing this doesn't actually make the file any different.)

If you want, I can adjust the default mode to be a mixed mode, where, when it runs out of modules it can inline separately, it emits a warning and then tries inlining them all at once.  Would this be satisfactory?  (The reason to inline them one by one is that it's generally much faster; it lets you eliminate entire modules that you're not using, rather than inlining them and then removing them line by line, and having to compile through all of them in the meantime.)

**Comment by RalfJung** [comment]
> Do you have a reproducing test case that doesn't depend on ssr / mathcomp / other non-bundled libraries?

No, sorry - it's not like I am working on 5 Coq developments that exhibit Coq bugs all the time ;-) . 
Note however that prelude.base does not depend on any external library.

Maybe what is upsetting the tool is some of the notation defined in there, which uses the `..` to define n-ary notation, which confuses the statement-splitter?

> (The reason to inline them one by one is that it's generally much faster; it lets you eliminate entire modules that you're not using, rather than inlining them and then removing them line by line, and having to compile through all of them in the meantime.)

Yes, I certainly agree that inlining one-by-one is awesome!

> If you want, I can adjust the default mode to be a mixed mode, where, when it runs out of modules it can inline separately, it emits a warning and then tries inlining them all at once. Would this be satisfactory? 

I don't know, since I don't know the tool well enough to entirely understand what you are saying. What I am doing right now is call the tool *again*, with `--no-minimize-before-inlining`, on the output that it produced in the first run. That way I get post of the speed benefit, since `prelude.base` does not actually import anything (except for base Coq stuff). If that's what you propose to do automatically, then yes, I think that would be a good mitigation. Of course, this doesn't fix whatever it is that makes the tool unable to do the inlining in the first place.

**Comment by RalfJung** [comment]
It turns out that calling the tool with `--no-minimize-before-inlining` requires a lot of manual work, not only because of the `..`-notations, but also because for some reason, the tool seems to break many of the other notations in a way that results in Coq saying "Cannot determine the level". Probably, the actual bug is not about the inliner, but about the tool failing after inlining `prelude/base.v`.

To reconstruct this without involving ssreflect:

*  Check out https://gitlab.mpi-sws.org/FP/iris-coq.git
*  Go to commit 946ed37
*  Run `find-bug.py -Q . "" prelude/prelude.v test.v` (to see the inliner fail, as in, not completely inline this file)
*  Run `find-bug.py --no-minimize-before-inlining -Q . "" prelude/prelude.v test.v` (to see the tool struggle with the contents of prelude/base.v)

The last call outputs:
```
The corresponding regular expression is 'File "[^"]+", line ([0-9]+), characters [0-9-]+:\n(Error\:\ The\ reference\ this\_lemma\_does\_not\_exist\ was\ not\ found\ in\ the\ current\\nenvironment\.)'.
Is this correct? [(y)es/(n)o] y

Sanity check passed.

Now, I will attempt to strip repeated newlines and trailing spaces from this file...

Succeeded in stripping newlines and spaces.

Now, I will attempt to strip the comments from this file...

Succeeded in stripping comments.

In order to efficiently manipulate the file, I have to break it into statements.  I will attempt to do this by matching on periods.
If you have periods in strings, and these periods are essential to generating the error, then this process will fail.  Consider replacing the string with some hack to get around having a period and then a space, like ["a. b"%string] with [("a." ++ " b")%string].
You have the following strings with periods in them:
"X ≡{ Γ1 , Γ2 , .. , Γ3 } Y"
"'[' X  ≡{ Γ1 , Γ2 , .. , Γ3 }  '/' Y ']'"
"(≡{ Γ1 , Γ2 , .. , Γ3 } )"
"{[ x ; y ; .. ; z ]}"
"X ⊆{ Γ1 , Γ2 , .. , Γ3 } Y"
"'[' X  ⊆{ Γ1 , Γ2 , .. , Γ3 }  '/' Y ']'"
"(⊆{ Γ1 , Γ2 , .. , Γ3 } )"
"X ⊈{ Γ1 , Γ2 , .. , Γ3 } Y"
"X  ⊈{ Γ1 , Γ2 , .. , Γ3 }  Y"
"(⊈{ Γ1 , Γ2 , .. , Γ3 } )"
"Xs ⊆{ Γ1 , Γ2 , .. , Γ3 }* Ys"
"Xs  ⊆{ Γ1 , Γ2 , .. , Γ3 }*  Ys"
"(⊆{ Γ1 , Γ2 , .. , Γ3 }* )"
"X ⊥{ Γ1 , Γ2 , .. , Γ3 } Y"
"X  ⊥{ Γ1 , Γ2 , .. , Γ3 }  Y"
"Xs ⊥{ Γ1 , Γ2 , .. , Γ3 }* Ys"
"Xs  ⊥{ Γ1 ,  Γ2 , .. , Γ3 }*  Ys"

Non-fatal error: Failed to split file to statements and preserve the error.  
The new error was:
File "/tmp/tmpV1Dqqr.v", line 241, characters 0-67:
Error: Cannot determine the level.

Split not saved.
I will not be able to proceed.
```

However, even after removing all the lines with `..`, the error remains.

**Comment by JasonGross** [comment]
Ugh, really?  The issue (in both cases, actually, since the default options _do_ try to inline `prelude.base`, but revert it after that fails), is that Coq accepts this:
```coq
Reserved Notation "(∪ *) ".
```
but if I say
```coq
Reserved Notation "(∪  *)  ".
```
Coq complains that it can't determine the level.  I've [reported a bug in Coq](https://coq.inria.fr/bugs/show_bug.cgi?id=4538), but I'll see if I can figure out where my code is adding the extra spaces (possibly an off-by-one error in some string splitting code).

**Comment by RalfJung** [comment]
Oh wow^^.

However, as far as I know, spaces actually have semantics in Notation. In particular, double-space means that the user *has* to write a space there, whereas single-space just separates tokens, but during parsing, Coq will accept these two tokens immediately following each other.

Quoting <https://coq.inria.fr/distrib/8.5/refman/Reference-Manual014.html#Notation>:
> This is performed by adding extra spaces between the symbols and parameters: each extra space (other than the single space needed to separate the components) is interpreted as a space to be inserted by the printer.

So, these warnings about `..` can just be ignored?

**Comment by JasonGross** [comment]
> is interpreted as a space to be inserted by the printer.

To me, this says that extra spaces only have semantics to the printer, not to the parser.  I don't see anything that gives them semantics to the parser.

I've updated the bug-minimizer to suppress the warnings about `..`; they only trigger if you have a number of `.`s not equal to 2 or 3, followed by whitespace, in a string.

**Comment by JasonGross** [comment]
Okay, so, the issue is this block of code:
```python
def strip_comments(contents):
    """Strips the comments from coq code in contents.

    The strings in contents are only preserved if there are no
    comment-like tokens inside of strings.  Stripping should be
    successful and correct, regardless of whether or not there are
    comment-like tokens in strings.

    The behavior of this method is undefined if there are any
    notations which change the meaning of '(*', '*)', or '"'."""
    contents = contents.replace('(*', ' (* ').replace('*)', ' *) ')
    tokens = contents.split(' ')
    rtn = []
    is_string = False
    comment_level = 0
    for token in tokens:
        if is_string:
            if token.count('"') % 2 == 1: # there are an odd number of '"' characters, indicating that we've ended the string
                is_string = False
            rtn.append(token)
        elif token == '(*':
            comment_level += 1
        elif comment_level > 0:
            if token == '*)':
                comment_level -= 1
        elif token.count('"') % 2 == 1: # there are an odd number of '"' characters, so we're starting a string
            is_string = True
            rtn.append(token)
        else:
            rtn.append(token)
    return ' '.join(rtn).strip('\n\t ')
```
and in particular the ```.replace('*)', ' *) ')```.  I'll see if I can correct for this, though I'm curious if you have any ideas for better comment-stripping code.

**Comment by cpitclaudel** [comment]
Nothing very smart. It looks for (possibly nested) pairs of  `(*` and `*)`.

**Comment by RalfJung** [comment]
Thanks a lot, I can confirm that this also fixes the problem as reported originally, i.e., with files that involve ssreflect. This is awesome :)

> though I'm curious if you have any ideas for better comment-stripping code.

Uh, nothing smart, really. I suppose the obvious one doesn't work for some reason: Use a tiny stack machine instead of regexp's that can properly detect whether we are in a string, or in a comment (and how deeply nested the comment is), and discards `(*` and `*)` if we are in a string.

**Comment by JasonGross** [comment]
I had that initially, but it was somewhat complicated to maintain and ensure correctness of, and might also have been slower than python's regular expressions.  (In particular, the trouble is lexing, not parsing, and a stack machine for the lexer was complicated to maintain.)
