### ISSUE TITLE
Minimizer runs into endless (?) loop

### ISSUE THREAD

**Issue by RalfJung** [JasonGross/coq-tools#25]
Steps to reproduce:
* Check out https://gitlab.mpi-sws.org/FP/iris-coq.git, commit f3c76cb7
* Run `find-bug.py -Q . "" algebra/cmra.v evar.v`

This takes a while. After about an hour (on my system), `evar.v` is a reasonably minimized file. However, the script does not terminate. Instead, it starts to print this:
```
getting evar.v
getting evar.glob
make -k -f - evar.glob
"/home/r/bin/coq-8.5/bin/coqdep" -c -Q "." "" "evar.v" > "evar.v.d" || ( RV=$?; rm -f "evar.v.d"; exit ${RV} )
coqc  -q  -Q "." ""   evar
File "./evar.v", line 194, characters 0-16:
Anomaly: cvtac's exception: Logic.RefinerError(_). Please report.
/tmp/Gm0CWaXA:314: recipe for target 'evar.glob' failed
make: *** [evar.glob] Error 129
getting evar.v
getting evar.glob
make -k -f - evar.glob
"/home/r/bin/coq-8.5/bin/coqdep" -c -Q "." "" "evar.v" > "evar.v.d" || ( RV=$?; rm -f "evar.v.d"; exit ${RV} )
coqc  -q  -Q "." ""   evar
File "./evar.v", line 194, characters 0-16:
Anomaly: cvtac's exception: Logic.RefinerError(_). Please report.
/tmp/Gmhpysh8:314: recipe for target 'evar.glob' failed
make: *** [evar.glob] Error 129
getting evar.v
getting evar.glob
make -k -f - evar.glob
"/home/r/bin/coq-8.5/bin/coqdep" -c -Q "." "" "evar.v" > "evar.v.d" || ( RV=$?; rm -f "evar.v.d"; exit ${RV} )
coqc  -q  -Q "." ""   evar
File "./evar.v", line 194, characters 0-16:
Anomaly: cvtac's exception: Logic.RefinerError(_). Please report.
/tmp/GmSkSYoC:314: recipe for target 'evar.glob' failed
make: *** [evar.glob] Error 129
```
over and over again. I made a copy of `evar.v` and diff'ed that copy against the current version, which revealed that `evar.v` is bouncing back and forth between two versions whose diff is
```
$ diff -u evar.bak evar.v
--- evar.bak	2016-02-21 18:33:27.582579903 +0100
+++ evar.v	2016-02-21 18:34:36.415234221 +0100
@@ -6,8 +6,8 @@
 Tactic Notation "admit" := case proof_admitted.
 End AdmitTactic.
 Require Coq.Program.Program.
-Require mathcomp.ssreflect.ssreflect.
 Require Coq.Unicode.Utf8.
+Require mathcomp.ssreflect.ssreflect.
 
 (* -*- mode: coq; coq-prog-args: ("-emacs" "-Q" "." "" "-top" "cmra") -*- *)
 (* File reduced by coq-bug-finder from original input, then from 1113 lines to 184 lines *)
```
I was not patient enough to let it run like that more than a few minutes. Considering that usually, `find-bug` does the compilation "in background" without putting the output on the console, I was pretty sure something had already gone wrong earlier.

**Comment by JasonGross** [comment]
Now fixed. Thanks for the report!

**Comment by JasonGross** [comment]
It's actually the case that some of the compilation is printed on the console, but it generally only compiles in this way once for each freshly inlined module, so the console gets filled with other information.  What you saw here was an endless loop where the file was changing back and forth even though there were no modules to be inclined.
