### ISSUE TITLE
find-bug forgets arg -impredicative-set at some point

### ISSUE THREAD

**Issue by jonleivent** [JasonGross/coq-tools#27]
See attached output.  

The command was: python /home/jil/git/coq-tools/find-bug.py -R "." mindless --arg " -impredicative-set" tctree.v ecasebug.v

The original ecasebug.v file find-bug produced needed some editing with respect to requires/imports/exports to get to the right bug.

[fbecasebug.txt](https://github.com/JasonGross/coq-tools/files/275506/fbecasebug.txt)

**Comment by JasonGross** [comment]
The solution to this, I believe, will be to update [the `coq_makefile` call to pass the relevant arguments](https://github.com/JasonGross/coq-tools/blob/master/import_util.py#L204)
