### ISSUE TITLE
find-bug.py: error when passing a list of warnings via command line options

### ISSUE THREAD

**Issue by anton-trunov** [JasonGross/coq-tools#39]
When I try to silence warnings like using `-w none`:
```
find-bug.py --arg "-w none" test.v bug.v
```

I get this error message:
```
Running command: "coqc" "-R" "." "Top" "-top" "test" "-w none" "/var/folders/x3/124x63dn1hn4hd_ydg8txzt40000gn/T/tmpxPpCLq.v" "-q"
The timeout has been set to: 2

This file produces the following output when Coq'ed:
coqc: -w none: no such file or directory

Does this output display the correct error? [(y)es/(n)o]
```

Apparently, `coqc` does not like quotation marks here, because it works if I call it like so:
```
coqc -w none test.v
```

The same error happens if I try to pass an explicit (comma-separated) list of warnings via command line.

**Comment by JasonGross** [comment]
You can use `find-bug.py --arg=-w --arg=none test.v bug.v`.  I'll see if I can make `find-bug.py` emit a warning when you pass a string that starts with `"-w "` to `--arg`.  I'd rather not special-case the actual behavior of `--arg`, which is "pass the quoted things you give `--arg` to `coqc`, in the order that you give them".

**Comment by anton-trunov** [comment]
Ah, didn't think of that solution. Thanks!
