### ISSUE TITLE
Prune the file before inlining

### ISSUE THREAD

**Issue by gmalecha** [JasonGross/coq-tools#5]
I've tried this on a few things, and I've noticed that it might be useful to run a pre-pruning phase before inlining. In some of my cases there are often a lot of definitions that are not necessary but also introduce dependencies. If you prune them before inlining all of the dependencies then it is possible that the number of dependencies that are inlined could be shrunk by a huge amount.

**Comment by JasonGross** [comment]
Indeed.  This has been on my todo list for a number of months.  The way I want to do it is to modularize the inlining code a bit more; currently, it inlines everything at once.  Instead, it should be able to inline one module at a time.  Then I can add "inline last module" as just another optimization to run (though one that needs a bit more care and tooling), and offer a modes where inlining is done at the beginning, or one file at a time, or all at once, but only after pruning the existing file.

A further optimization would be to copy over the directory structure and dependencies, and ensure that the script can compile all of them.

(If you happen to have time, and want to contribute a PR to do this, I'd welcome it.  I can point you to the right bits of code, and a slightly more fleshed out outline, if you'd like.)

**Comment by JasonGross** [comment]
@gmalecha, want to try out `--minimize-before-inlining`, and let me know how it works for you, if you still have the relevant files around?
