### ISSUE TITLE
Odd breaking of lines

### ISSUE THREAD

**Issue by beta-ziliani** [JasonGross/coq-tools#54]
The tool is breaking sentences in the middle of words, breaking proofs. For instance, when trying to minimize the attached file it fails with an error `The reference r was not found in the current environment.`, and when looking at the generated tmp file, this is coming from a broken tactic:
```
  r
  eflexivity.
```

I'm in an Ubuntu 18.04 with Coq version: 8.11.1 (May 2020) compiled on May 16 2020 19:49:12 with OCaml 4.09.1, Python 2.7.17.

[minimizing file and tmp file.zip](https://github.com/JasonGross/coq-tools/files/5343273/minimizing.file.and.tmp.file.zip)

**Comment by JasonGross** [comment]
I believe this was due to the use of unicode characters: `coqtop -time` emits character numbers in bytes, whereas python3 was expecting characters.  I've fixed this in https://github.com/JasonGross/coq-tools/commit/f17dd3320676d62cc7d9d7e0fbb9a11efae0bc66
