### ISSUE TITLE
ValueError on remove action when force_keep is true

### ISSUE THREAD

**Issue by jadephilipoom** [JasonGross/coq-tools#55]
Running into a ValueError  with `From _ Require Export` statements: 
```
$ cat ../B.v
From Coq Require Export ZArith.ZArith.
$ ./minimize-requires.py --absolutize ../B.v
getting ../B.v
getting ../B.glob
Running coq on initial contents...
Successful change
Traceback (most recent call last):
  File "./minimize-requires.py", line 273, in <module>
    raise e
ValueError
```
This error is fixed by either:
- Changing the `From _ Require` syntax to just `Require Export Coq.ZArith.ZArith`
- Removing `--absolutize`
- Changing `Export` to `Import`

The error is raised by this line:
https://github.com/JasonGross/coq-tools/blob/762df647adc1696a5fc255ab9e12ddf474245bca/minimize-requires.py#L144
...where there is an if/elif clause with the following clauses:
```
if action == SKIP or action is None:
  [...]
elif action == ABSOLUTIZE: 
  [...]
elif action == REMOVE and not force_keep: 
  [...]
else: 
  raise ValueError 
```
By making the error print out `action` and `force_keep`, I found that this is happening because `action` is `REMOVE` and `force_keep` is true, so the third clause fails. I was able to hotfix it locally by changing to:
```
if action == SKIP or action is None:
  [...]
elif action == ABSOLUTIZE: 
  [...]
elif action == REMOVE:
  if force_keep:
    <same as ABSOLUTIZE>
  else: 
    <original REMOVE clause>
else: 
  raise ValueError 
```
...but there's probably something more going on here, and that only works for me because I'm always absolutizing.

**Comment by JasonGross** [comment]
Thanks for reporting this, and I finally got around to fixing it.  I think the relevant issue was that I was being inconsistent about the meaning of `ValueError`.  I've fixed this with https://github.com/JasonGross/coq-tools/commit/2f016f1ebd93eebad033e8799a2bf5e1492bbc6f#diff-2d25e47a1cade7410f7495270fd4f5b85d743de08c07f854368693b5c8ff9f75

Btw, the `--absolutize` code is more robust, now, and should now correctly handle `From ... Require ...` by turning them into `Require ...`
