### ISSUE TITLE
find-bug.py fails to minimize

### ISSUE THREAD

**Issue by Columbus240** [JasonGross/coq-tools#61]
Running find-bug.py on some input data (see below) gives the following unexpected output.
```
...
In order to efficiently manipulate the file, I have to break it into definitions.  I will now attempt to do this.
Sending statements to coqtop...
Done.  Splitting to definitions...

Non-fatal error: Failed to split file to definitions and preserve the error.
The new error was:
File "/tmp/tmpt4i4fdva.v", line 57, characters 2-5:
Error: The reference spl was not found in the current environment.


Split not saved.
I will not be able to proceed.
```
Is this a bug in find-bug.py? The file looks relatively simple to me. I don’t understand why it fails.
I’m sorry that the example is relatively large. In fact, it is so large precisely because find-bug.py fails.

### To reproduce
Have coq v8.13.2 or the development version installed and perform the following commands (apropriately adapted if necessary).
```
$ git clone --depth 1 -b SCNT https://github.com/Columbus240/category-theory
$ cd category-theory
$ make Structure/Cone/Natural/Transformation.vo
```
This will result in an error of the sort:
```
COQC Structure/Cone/Natural/Transformation.v
File "./Structure/Cone/Natural/Transformation.v", line 32, characters 0-4:
Error:
Anomaly
"Universe Category.Structure.Cone.Natural.Transformation.703 undefined."
Please report at http://coq.inria.fr/bugs/.
```
Note that the error appears exactly when the command `Qed.` is reached.
Then do the following to produce the error I mentioned at the top.
```
$ python /path/to/coq-tools/find-bugs.py -R . Category Structure/Cone/Natural/Transformation.v SCNT.v
```

**Comment by JasonGross** [comment]
Could be.  Might be a unicode issue, locations are very finicky.  And they differ between python 2 and 3.  Can you check that you have the latest version of the minimizer (/let me know what commit you're using), tell me your python version, and run 
```
python /path/to/coq-tools/find-bugs.py -R . Category Structure/Cone/Natural/Transformation.v SCNT.v temp.v --no-deps
```
and then paste the contents of `temp.v` for me here after it fails (or it's possible `--no-deps` fixes this).

**Comment by JasonGross** [comment]
Also, thanks for the report, and I hope the minimizer has been helpful!

**Comment by Columbus240** [comment]
Erm, thanks for mentioning versions. I noticed that I used an old version of find-bug.py (commit 762df64 from 2020-09-24). The current master branch works fine, without errors, though there’s something else for which I’ll make a new issue.

The minimizer has been very helpful, when I found anomalies etc. It also somehow made dealing with huge codebases less daunting, since I always knew: if an error arises, I can minimize it. Exchanging human work with computer work :)
Thanks for building and maintaining it.

And by the way, I don’t know when I last encountered issues with Unicode notations. I think most bugs in this area have already been found. This time the problem wasn’t with Unicode, since unfolding all notations to their definitions also made the problem appear.

**Comment by JasonGross** [comment]
I'm glad to hear it's been helpful!

> I don’t know when I last encountered issues with Unicode notations

Ah, I'm saying that the bug minimizer itself has historically had a lot of problems with files containing unicode, though I think I've now ironed out most of them.  Coq handles unicode relatively painlessly (though there was once a critical bug involving mishandling of unicode by the native compiler that allowed a proof of `False`).
