### ISSUE TITLE
filename_of_lib should prefer files that exist to ones that don't

### ISSUE THREAD

**Issue by JasonGross** [JasonGross/coq-tools#65]
An example of something that might have been fixed by https://github.com/JasonGross/coq-tools/issues/56

When multiple physical paths are bound to the same logical path, the bug minimizer chooses the first one at https://github.com/JasonGross/coq-tools/blob/035c090a935537c8669150e405ed9968976290c6/import_util.py#L81-L93 while Coq will prefer paths that exist.  We should do the same to avoid errors like https://github.com/coq/coq/pull/13072#issuecomment-857885217

**Comment by ejgallego** [comment]
Indeed you can use any of the APIs to get this information directly from Coq.
