### ISSUE TITLE
Support `-R foo bar`

### ISSUE THREAD

**Issue by JasonGross** [JasonGross/coq-tools#9]
Currently only `-R . bar` is supported.

**Comment by DanGrayson** [comment]
Suggestion for a quick way to prevent user confusion about that: give an error message ```-R foo bar``` is used.

**Comment by aa755** [comment]
There is a simple workaround for now : `cp -r foo /usr/local/lib/coq/user-contrib/bar`
I was able to successfully use this workaround in my project.
